services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file:
      - ./src/main/resources/.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: pmt_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: