hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pmt_db
    username: ${PMT_DB_USER}
    password: ${PMT_DB_PASSWORD}
  hbm2ddl.auto: none
  show_sql: true
  format_sql: true

liquibase:
  changeLogName: db/changelog/changelog.yml
  schemaName: service
  defaultSchemaName: app
  logging:
    level: INFO
    file: /var/log/liquibase.log

logging:
  level:
    liquibase: OFF
    org.hibernate: OFF
