hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pmt_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  hbm2ddl.auto: none
  show_sql: true
  format_sql: true

liquibase:
  changeLogName: db/changelog/changelog.yml
  schemaName: service
  defaultSchemaName: app

