hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: ${HIBERNATE_CONNECTION_URL}
    username: ${PMT_DB_USER}
    password: ${PMT_DB_PASSWORD}
  hbm2ddl.auto: none
  show_sql: false
  format_sql: false

liquibase:
  enabled: true
  changeLogName: db/changelog/changelog.yml
  schemaName: service
  defaultSchemaName: app

