DROP DATABASE IF EXISTS pmt_db;
DROP ROLE IF EXISTS root;



CREATE USER root WITH PASSWORD '1';
CREATE DATABASE pmt_db;
GRANT ALL PRIVILEGES ON DATABASE pmt_db TO root;

CREATE SCHEMA service;
CREATE SCHEMA app;
GRANT ALL PRIVILEGES ON SCHEMA service TO root;
GRANT ALL PRIVILEGES ON SCHEMA app TO root;
